# Generated by Django 5.2.1 on 2025-06-09 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mode_paiement', models.CharField(choices=[('carte bancaire', 'Carte Bancaire'), ('PayPal', 'PayPal'), ('portefeuille électronique', 'Portefeuille Électronique'), ('Mobile Money', 'Mobile Money')], max_length=25)),
                ('statut', models.CharField(choices=[('effectué', 'Effectué'), ('en attente', 'En Attente'), ('échoué', 'Échoué')], default='en attente', max_length=20)),
                ('date_paiement', models.DateTimeField(auto_now_add=True)),
                ('livraison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.livraison')),
            ],
        ),
    ]
