# Generated by Django 5.2.1 on 2025-06-10 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
        ('demande', '0002_demande_livraison_delete_colis'),
        ('livreurs', '0005_alter_livreur_numero_immatriculation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livraison',
            name='demande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livraisons_delivery', to='demande.demande'),
        ),
        migrations.AlterField(
            model_name='livraison',
            name='livreur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livreurs.livreur'),
        ),
        migrations.DeleteModel(
            name='Demande',
        ),
        migrations.DeleteModel(
            name='Livreur',
        ),
    ]
