# Generated by Django 5.2.1 on 2025-06-10 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_alter_livraison_demande_alter_livraison_livreur_and_more'),
        ('livreurs', '0006_remove_livreur_disponibilite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livraison',
            name='livreur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='livreurs.livreur'),
        ),
    ]
