# Generated by Django 5.2.1 on 2025-06-14 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_alter_livraison_livreur'),
        ('demande', '0004_alter_demande_photo_colis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livraison',
            name='demande',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='livraison_delivery', to='demande.demande'),
        ),
    ]
