# Generated by Django 5.2.1 on 2025-05-26 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_utilisateur_entreprise_delete_entreprise'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='username',
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='localisation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
