# Generated by Django 5.2.1 on 2025-05-29 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_utilisateur_username_utilisateur_localisation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='entreprise',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='localisation',
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
