# Generated by Django 5.2.1 on 2025-05-30 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_utilisateur_entreprise_alter_utilisateur_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('client', 'Client'), ('livreur', 'Livreur')], max_length=20),
        ),
    ]
