# Generated by Django 5.2.1 on 2025-06-09 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_utilisateur_date_inscription_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='entreprise',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='secret_code',
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='site_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
