# Generated by Django 5.2.1 on 2025-06-09 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_utilisateur_entreprise_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('client', 'Client'), ('livreur', 'Livreur')], default='client', max_length=20),
        ),
    ]
