# Generated by Django 5.2.1 on 2025-06-10 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_utilisateur_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='username',
        ),
    ]
