# Generated by Django 5.2.1 on 2025-05-27 15:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 27, 16, 19, 10, 527587, tzinfo=datetime.timezone.utc)),
        ),
    ]
