# Generated by Django 5.2.1 on 2025-05-29 11:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp', '0003_alter_otp_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 29, 12, 23, 54, 947201, tzinfo=datetime.timezone.utc)),
        ),
    ]
