# Generated by Django 5.2.1 on 2025-05-29 19:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp', '0017_alter_otp_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 29, 20, 36, 11, 291420, tzinfo=datetime.timezone.utc)),
        ),
    ]
