# Generated by Django 5.2.1 on 2025-05-30 00:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp', '0020_alter_otp_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 30, 1, 6, 16, 764458, tzinfo=datetime.timezone.utc)),
        ),
    ]
