# Generated by Django 5.2.1 on 2025-06-10 10:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demande', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Demande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nature_colis', models.CharField(blank=True, max_length=255, null=True)),
                ('dimensions', models.CharField(blank=True, max_length=100, null=True)),
                ('poids', models.DecimalField(decimal_places=2, max_digits=10)),
                ('photo_colis', models.URLField(blank=True, null=True)),
                ('adresse_depart', models.TextField()),
                ('adresse_destination', models.TextField()),
                ('mode_livraison', models.CharField(choices=[('express', 'Express'), ('standard', 'Standard'), ('economique', 'Économique')], max_length=20)),
                ('statut_demande', models.CharField(choices=[('en attente', 'En attente'), ('pris en charge', 'Pris en charge'), ('en transit', 'En transit'), ('livré', 'Livré')], default='en attente', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Livraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='livraison_demande', to='demande.demande')),
            ],
        ),
        migrations.DeleteModel(
            name='Colis',
        ),
    ]
