# Generated by Django 5.2.1 on 2025-06-10 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demande', '0002_demande_livraison_delete_colis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demande',
            name='adresse_depart',
        ),
        migrations.RemoveField(
            model_name='demande',
            name='adresse_destination',
        ),
    ]
