# Generated by Django 5.2.1 on 2025-05-29 19:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livreurs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livreur',
            name='photo_livreur',
        ),
        migrations.RemoveField(
            model_name='livreur',
            name='user',
        ),
        migrations.AddField(
            model_name='livreur',
            name='date_creation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='livreur',
            name='utilisateur',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='livreur_profile', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='livreur',
            name='photo_moto',
            field=models.TextField(blank=True, null=True),
        ),
    ]
