# Generated by Django 5.2.1 on 2025-05-29 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livreurs', '0002_remove_livreur_photo_livreur_remove_livreur_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livreur',
            name='photo_livreur',
            field=models.TextField(blank=True, null=True),
        ),
    ]
