# Generated by Django 5.2.1 on 2025-05-29 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livreurs', '0003_livreur_photo_livreur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livreur',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='livreur',
            name='longitude',
        ),
    ]
