# Generated by Django 5.2.1 on 2025-06-10 11:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livreurs', '0005_alter_livreur_numero_immatriculation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livreur',
            name='disponibilite',
        ),
        migrations.RemoveField(
            model_name='livreur',
            name='nombre_livraisons',
        ),
        migrations.RemoveField(
            model_name='livreur',
            name='numero_immatriculation',
        ),
        migrations.RemoveField(
            model_name='livreur',
            name='statut',
        ),
        migrations.AddField(
            model_name='livreur',
            name='immatriculation_moto',
            field=models.CharField(default='ABC-123', max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message="Le numéro d'immatriculation doit contenir uniquement des lettres majuscules, des chiffres et des tirets.", regex='^[A-Z0-9-]+$')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='livreur',
            name='statut_livreur',
            field=models.CharField(choices=[('actif', 'Actif'), ('bloqué', 'Bloqué'), ('en révision', 'En révision')], default='en révision', max_length=20),
        ),
    ]
