# Generated by Django 5.2.1 on 2025-06-12 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livreurs', '0006_remove_livreur_disponibilite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livreur',
            name='photo_livreur',
            field=models.ImageField(blank=True, null=True, upload_to='photos_livreurs/'),
        ),
        migrations.AlterField(
            model_name='livreur',
            name='photo_moto',
            field=models.ImageField(blank=True, null=True, upload_to='photos_motos/'),
        ),
    ]
